.clang-format, .clang-tidy, .github/workflows/clang_format_check.yml, .github/workflows/cmake_debug.yml, .github/workflows/cmake_package_debug.yml, .github/workflows/cmake_package_release.yml, .github/workflows/cmake_release.yml, CMakeLists.txt, cmake/RunClangFormat.cmake, include/fkYAML/Exception.hpp, include/fkYAML/Iterator.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeType.hpp, test/node_class_test/NodeClassTest.cpp, test/node_class_test/NodeClassTest.hpp, test/node_class_test/main.cpp
This library now supports clang-format & clang-tidy.  
clang-format-16 & clang-tidy-16 are checked in my develop environment on Windows10 Home edition.  
Other versions may be currently unsupported, so further investigation may be necessary.  
clang-format is also supported while executing GitHub Actions, but clang-tidy is not.  
As for clang-tidy, implementation will be done in another issue later on.
=> #8 support clang format & clang tidy

.github/workflows/cmake_debug.yml, .github/workflows/cmake_release.yml, CMakeLists.txt, cmake/AddSanitizers.cmake, test/unit_test/CMakeLists.txt, test/unit_test/main.cpp
A new build option to build the unit test app with some sanitizers has been added.  
To enable sanitizers, add `-DFK_YAML_RUN_SANITIZERS=ON` when configuring fkYAML library with CMake.  
Currently, this option is executed only on ubuntu during GitHub Actions.
=> #28 add sanitizers to unit test app

.github/workflows/coverage.yml, .github/workflows/ubuntu.yml, CMakeLists.txt, README.md, test/unit_test/CMakeLists.txt
The test code coverage has been introduced to both CMake target & GitHub Actions' workflow job.  
This project will use Coveralls as a code coverage service.  
The current coverage on develop branch will be displayed on top of the README.md.  
The coverage rate will be growing upto 100% as much fastly as possible.
=> #45 add code coverage job

include/fkYAML/Assert.hpp, include/fkYAML/Deserializer.hpp, include/fkYAML/Iterator.hpp, include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeTypeTraits.hpp
Some static/runtime assertion checks have been added to fkYAML library to enhance its testability at compile-time/runtime.  
Runtime assertions can be customized by users by defining their own FK_YAML_ASSERT implementation before including each fkYAML header file.
=> #57 Added static/runtime assertion checks

include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/LexicalAnalyzerClassTest.cpp, test/unit_test/NodeClassTest.cpp, thirdparty/imapdl/filterbr.py
Unit test cases against not-yet-covered lines have been added for LexicalAnalyzer class (& some for BasicNode class).  
To correctly gather & upload coverage data, a Python script has also been added from other repository without any changes.  
The script is to be executed when `generate_test_coverage` is the CMake build target (available on local machine & CI workflows).
=> #33 Added unit test cases for LexicalAnalyzer class

.github/workflows/ubuntu.yml, CMakeLists.txt, clang_tidy/CMakeLists.txt, clang_tidy/ClangTidyHelper.cpp, cmake/RunClangFormat.cmake, include/fkYAML/Assert.hpp, include/fkYAML/Deserializer.hpp, include/fkYAML/Iterator.hpp, include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeTypeTraits.hpp, test/unit_test/CMakeLists.txt
Clang-tidy is supported in CMake scripts for fkYAML library.  
It is configured to be running:
- when fkYAML library is the main CMake target (specify `-DFK_YAML_RunClangTidy=OFF` to disable this configuration)
- or when source code changes detected by GitHub Actions.
=> #14 Support clang-tidy on CI

include/fkYAML/Deserializer.hpp, include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeType.hpp, include/fkYAML/YAMLVersionType.hpp, test/unit_test/DeserializerClassTest.cpp, test/unit_test/LexicalAnalyzerClassTest.cpp, test/unit_test/NodeClassTest.cpp
Lexical analysis/deserialization of YAML version directives are supported in fkYAML library.  
The supported YAML versions are 1.1 and 1.2.(The library defaults to 1.2 without any specification.)  
Each Node objects can be used to reference YAML version used in deserialization.  
Tag directives are currently not supported, but will be implemented in the near future PR.
=> #61 Support YAML version directives

.github/workflows/ubuntu.yml, CMakeLists.txt, cmake/ci.cmake
Script contents have been modified to support self-hosted runner of GitHub Actions.  
The self-hosted runner is a private project which contains various tools(compilers, linters, testers etc) to execute more compilicated tests during GitHub Actions.
=> #64 add self-hosted runner for GitHub Actions

.github/workflows/ubuntu.yml, test/cmake_fetch_content_test/project/CMakeLists.txt
Referenced git tag in FetchContent test have been modified to the head of develop branch.  
In addition, self-hosted runners have been separated in terms of compiler types (gcc, clang) to speed up execution of CI jobs.
=> #70 Fixed Git tag for FetchContent test

include/fkYAML/Serializer.hpp, test/unit_test/CMakeLists.txt, test/unit_test/SerializerClassTest.cpp
Serialization feature has been added to fkYAML library.  
The output order of mapping node items depends on std::map implementation, i.e., not the insertion order.  
The above limitation will be fixed by implementing a custom map class which guarantees the insertion order of items within.
=> #5 implemented yaml node serializer

clang_tidy/ClangTidyHelper.cpp, include/fkYAML/Node.hpp, include/fkYAML/OrderedMap.hpp, include/fkYAML/Serializer.hpp, test/unit_test/CMakeLists.txt, test/unit_test/OrderedMapClassTest.cpp, test/unit_test/SerializerClassTest.cpp
The order of inserting mapping node items has been fixed to keep the insertion order, not weak comparison order like std::map objects have.  
This is because, as for YAML formatted files, the order of keys in the file seems to be somehow important for the readers to understand logical relations between YAML nodes.  
Such a fix has been realized by implementing `OrderedMap` class which behaves as a map-like container but still preserves the insertion order of keys.  
The `OrderedMap` class currently has its minimal implementation only to the extent to which it can be compiled successfully.  
The further implementation will be added when some additional features are necessary to achieve more complex behaviors.
=> #74 Fixed keeping insertion orders of mapping node items

include/fkYAML/Deserializer.hpp, include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeType.hpp, include/fkYAML/NodeTypeTraits.hpp, include/fkYAML/Serializer.hpp, test/unit_test/DeserializerClassTest.cpp, test/unit_test/LexicalAnalyzerClassTest.cpp, test/unit_test/NodeClassTest.cpp, test/unit_test/SerializerClassTest.cpp
Integer scalar data type has been changed to int64_t only.  
Not int64_t & uint64_t separately anymore.  
This is for clarity of implementation as well as usage.  
The acceptable range of integer values is therefore the one which int64_t can have: 4 bytes of buffer each for signed/unsigned in a single integer value.  
The unit test app has also support the above change, and all the test cases have passed successfully.
=> #85 change integer scalar data type to int64_t only

.github/workflows/macos.yml, .github/workflows/windows.yml, README.md
New compilers have been added to the supported compiler list.  
The fkYAML library is built and unit-tested with those compilers with successful results.  
Newly supported compilers are as follows:  
| Compiler | Operating System | CI provider |
|----------|------------------|-------------|
| AppleClang 11.0.3.11030032 | macOS 11.7.9 | GitHub Actions |
| AppleClang 12.0.0.12000032 | macOS 11.7.9 | GitHub Actions |
| AppleClang 12.0.5.12050022 | macOS 11.7.9 | GitHub Actions |
| AppleClang 13.0.0.13000029 | macOS 11.7.9 | GitHub Actions |
| AppleClang 13.0.0.13000029 | macOS 12.6.8 | GitHub Actions |
| AppleClang 13.1.6.13160021 | macOS 12.6.8 | GitHub Actions |
| MinGW-64 8.1.0 | Windows-10.0.17763 | GitHub Actions |
| MinGW-64 12.2.0 | Windows-10.0.20348 | GitHub Actions |
=> #83 Add compiler support on Windows & macOS

include/fkYAML/Deserializer.hpp, test/unit_test/DeserializerClassTest.cpp
Unit test cases for Deserializer class have been added to the unit test app.  
During the implementation above, the Deserializer class source file has also been refactored to make it a little bit clearer & readable.
=> #34 add unit tests for deserializer

.github/workflows/ubuntu.yml, README.md, test/unit_test/CMakeLists.txt
Memory leak check with Valgrind has been added to this project to GitHub Actions workflows.  
On local machines with Valgrind installed, the following commands execute the same check.  
```sh
$ cd path/to/fkYAML
$ mkdir build && cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Debug -DFK_YAML_BUILD_TEST=ON -DFK_YAML_RUN_VALGRIND=ON
$ cmake --build . --config Debug
$ ctest -C Debug -T memcheck
```
#101
=> #101 added memory leak check with Valgrind

.github/workflows/ubuntu.yml, README.md, cmake/ci.cmake
Before this PR, GitHub Actions workflows use GCC compilers which have been pre-installed into the self-hosted runner.  
Since version management would be harder as development evolves, however, I've decided to change the management strategy to the one in which the workflows use the official docker images for GCC.  
Similar workflows which use Clang compilers still uses the ones pre-installed into the self-hosted runner, which will also be changed to using some docker images.
=> #109 Use official docker image for GCC during CI jobs

docs/Doxyfile.in, include/fkYAML/Deserializer.hpp, include/fkYAML/Iterator.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeTypeTraits.hpp, include/fkYAML/OrderedMap.hpp, include/fkYAML/Serializer.hpp
Currently, the API documentation of this project describes all the members of each class in the fkYAML library on GitHub Pages.  
The descriptions of private members could bring confusion to its readers, especially developers who just use the library, because of its too much concreteness.  
So, I would like to regulate the contents of the API documents to private members.  
See #113.
=> #113 Generate API documentation only for public members

Makefile
I have introduced the github-changelog-generator tool to the project to generate CHANGELOG.md automatically for future releases of the project.  
The routine command to use the tool has also been added to Makefile as part of update-version target.  
#120
=> #120 added target to use github-changelog-generator tool

.clang-tidy, Makefile, README.md, include/fkYAML/Deserializer.hpp, include/fkYAML/Exception.hpp, include/fkYAML/Iterator.hpp, include/fkYAML/LexicalAnalyzer.hpp, include/fkYAML/Node.hpp, include/fkYAML/NodeType.hpp, include/fkYAML/OrderedMap.hpp, include/fkYAML/Serializer.hpp, include/fkYAML/TypeTraits.hpp, include/fkYAML/YAMLVersionType.hpp, test/cmake_add_subdirectory_test/project/main.cpp, test/cmake_fetch_content_test/project/CMakeLists.txt, test/cmake_fetch_content_test/project/main.cpp, test/cmake_find_package_test/project/main.cpp, test/cmake_target_include_directories_test/project/main.cpp, test/unit_test/DeserializerClassTest.cpp, test/unit_test/ExceptionClassTest.cpp, test/unit_test/IteratorClassTest.cpp, test/unit_test/LexicalAnalyzerClassTest.cpp, test/unit_test/NodeClassTest.cpp, test/unit_test/OrderedMapClassTest.cpp, test/unit_test/SerializerClassTest.cpp
To enhance compatibility of naming conventions with existing STL implementation, almost all custom types in the project have been changed to the lower_snake_case format.  
One exception is applied to template arguments because they are conventionally named in UpperCamelCase format.  
Additionally, example codes in the README.md have also been changed to follow the changes in naming conventions.  
The above changes gurantee no compatibility with the earlier version of the fkYAML library.  
#123
=> #123 Change naming conventions to lower_snake_case

tool/clang_tidy/CMakeLists.txt
With increase in the number of library source files, it has been more and more difficult to properly maintain clang_tidy_helper.hpp file.  
To decrease such an issue, the helper file has changed to be auto-generated depending on the existing .hpp files under include directory.
=> #136 Auto-generate a helper source file for the clang-tidy tool

test/unit_test/CMakeLists.txt
Related to #128 and #132, the source files under the detail directory has been missed when generating coverage data.  
This PR has fixed the issue above.
=> #128 fixed filtering source files to generate full-spec coverage

README.md
I have added descriptions for the changes related to #127.  
The added descriptions contain how to customize serialization/deserialization by implementing overloads of `to_node()` and `from_node()` functions with some cautions.
=> #127 Update examples in readme

include/fkYAML/detail/conversions/from_string.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_handler.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/meta/type_traits.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_from_string.cpp, test/unit_test/test_lexical_analyzer_class.cpp
In this PR, the `lexical_analyzer` class has been refactored by:
- implementing the `input_handler` class as a handler of an input adapter,
- implementing `from_string` template functions to generalize conversions from string tokens to native data type values,
- and deleting duplicate conversion checks for resulting token values.
Furthermore, some small fixes have also been applied such as typos in test case labels or splitting some too complicated functions into somewhat understandably sized ones.  
With the changes described above, backward compatibility is still guranteed since previous v0.1 releases.
=> #133 refactor lexer

Makefile, include/fkYAML/detail/macros/version_macros.hpp
Due to the change in locations of internal implementations, Makefile mistakingly assume the version_macros.hpp file path.  
Which makes internal library version checks executed wrongly.  
In this PR, I have fixed the wrong path in the Makefile.
=> Fix version_macros.hpp file path in Makefile

include/fkYAML/detail/output/serializer.hpp
Some unreachable lines in serializer class have been changed to get excluded from coverage data.  
I have no idea on how to reproduce such a line but it does happen.  
So, as a work-around, I just make lcov ignore those lines in generating coverage data.  
Related links: #150
=> #150 Excluded unreachable lines in serializer class test from coverage data

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
Unit test cases for missing lines/branches of lexical_analyzer class implementation, have been added/modified.  
To clean up implementation, unused functions/members have also been deleted.  
They might be re-implemented as a fixed version in some later PRs.  
Related links: #150
=> #150 added/modified unit tests for lexical_analyzer test

include/fkYAML/detail/meta/node_traits.hpp, include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
Before this PR, non-default `basic_node` template instance classes are not specialized for `swap()`.  
To improve the quality of user-defined customization of `basic_node` template class, I have replaced the overloaded version of `std::swap()` with the one defined in the `fkyaml` namespace.  
The library users will still be able to call swap() for `fkyaml::node` instances just as they did before this PR, which means that backward compatibility is still guranteed.
=> #145 Expand swap() support for basic node

include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/iterator.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_node_class.cpp
Warnings emitted while building the fkYAML library or its tests have been resolved to ensure the quality of the codebase.
=> #18 Resolve warnings while building library/tests

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/input_handler.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/iterator.hpp, include/fkYAML/node.hpp, include/fkYAML/ordered_map.hpp
Before this PR, some classes do not have default initial values for their own member variables.  
For such a class, each constructor should have　its member initializer list, and those list tend to be the same in every constructor.  
Sometimes those those classes have some uninitialized values at their constructors, which would potentially and unexpectedly cause undefined behaviours.  
To avoid duplicating boilerplates as well as missing initialization, I would like to introduce default initial values for member variables where they are missing.  
Related items: #164.
=> #164 Use default initial values for class member variables

include/fkYAML/detail/conversions/to_string.hpp, include/fkYAML/detail/output/serializer.hpp
Before this PR, `basic_serializer` class implements conversions from native data type values to strings.  
So, to_string() template functions have been added to abstract too concrete serialization process.  
This is assumed to be a foundation for outputs in the form of multi-byte strings. (Not implemented)
=> #158 Added to_string() for serialization of YAML nodes.

include/fkYAML/detail/meta/node_traits.hpp, include/fkYAML/detail/meta/type_traits.hpp, include/fkYAML/detail/node_ref_storage.hpp, include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_node_class.cpp, test/unit_test/test_node_ref_storage_class.cpp
It has been supported to construct basic_node objects with std::initializer_list object.  
As a helper class, node_ref_storage class has also been implemented to wrap basic_node {l|r}values in std::initializer_list objects, which aims to increase memory efficiency and thus performance in constructing a new basic_node object.  
Furthermore, Test cases for newly added public/private APIs have been added to cover the whole parts of the fkYAML library's implementation.  
Related items: #105.
=> #105 Support std::initializer_list in basic_node constructors

include/fkYAML/node.hpp, test/unit_test/test_ordered_map_class.cpp, test/unit_test/test_serializer_class.cpp
Currently, mapping nodes preserves the order of insertions by using ordere_map class.  
However, I noticed that YAML specification 1.2.2 defines mapping as “an unordered association of unique keys to values“.  
(See for more information [here](https://yaml.org/spec/1.2.2/#3221-mapping-key-order).)  
To follow the specification, basic_node class will be changed to use std::map as mapping container class by default.  
Note that std::unordered_map is not supported since it does not support the use of incomplete types on template instantiation.  
This change will change the serialization/deserialization results, but bring the fkYAML library more efficiency in performance.  
Lastly, the `ordered_map` class will still be available as an optional mapping container type for customization(, rather …
=> #167 Use std::map as the default mapping node type

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_handler.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_input_handler.cpp
Before this PR, the fkYAML library couldn't detect indentation width before each token of input buffers.  
Which resulted in wrong deserialization outputs with the following YAML formatted string:  
```yaml
foo:
bar: 123
baz: true   # This was the part of "foo" mapping node.
```
This PR has corrected the above issue and support multiple mapping nodes at different levels.
=> #175 support detecting indentation in deserialization

include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/meta/input_adapter_traits.hpp, include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_data/input_adapter_test_data.txt, test/unit_test/test_input_adapter.cpp, test/unit_test/test_node_class.cpp
Before this PR, there were no test cases only for input adapters.
To ensure that input adapters work as they are expected with no dependencies on the other classes, new test cases for input adapters have been added with some test data files.  
Along with the above implementation, some unused members in input adapter classes have been deleted.
=> #177 Add test for input adapters only

README.md, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/node.hpp, test/unit_test/test_input_adapter.cpp, test/unit_test/test_iterator_class.cpp, test/unit_test/test_node_class.cpp, test/unit_test/test_serializer_class.cpp
Along with developing the fkYAML library, some public APIs have become unnecessarily public.  
Taht is because more convenient APIs are introduced, such as basic_node constructor with `std::initializer_list` has covered factory methods of basic_node objects.  
Also, deserialization API overload has been removed which could possibly cause undefined behaviors.  
So, this PR has removed those APIs so that the fkYAML library will have more readable & understandable APIs.
=> #180 clean up public apis

test/unit_test/test_input_adapter.cpp
Valgrind detected possible memory leaks.  
It's turned out that the detection is the result of missing calls for flose() in input adapter tests.  
To ensure that it correctly checks the behaviors and data flows in the fkYAML library, this PR has fixed the issue described above.
=> #185 fixed missing calls for fclose() in input adapter tests

README.md, include/fkYAML/detail/conversions/to_node.hpp, include/fkYAML/detail/meta/stl_supplement.hpp, include/fkYAML/detail/node_ref_storage.hpp, test/unit_test/test_iterator_class.cpp, test/unit_test/test_node_class.cpp, test/unit_test/test_node_ref_storage_class.cpp, test/unit_test/test_serializer_class.cpp
Currently, constructing a string scalar node requires exactly the same type as basic_node::string_type as an argument type.  
This restriction had been forcing users to create a lot of boilerplate codes before this PR.  
To resolve the issue, this PR have supported compatible strings, e.g., character arrays or std::string_view (only with C++17 or later), as an argument of the basic_node constructor.
=> #187 support compatible strings as an argument in basic_node ctors

docs/mkdocs/docs/tutorials.md, docs/mkdocs/docs/tutorials/cmake_integration.md, docs/mkdocs/docs/tutorials/index.md, docs/mkdocs/mkdocs.yml
Tutorial pages have been created to the documentation to make it easier for users to understand what fkYAML is as well as what is possible with fkYAML through making a sample CMake project which uses fkYAML.
=> #179 Created tutorial pages

docs/mkdocs/docs/api/basic_node/begin.md, docs/mkdocs/docs/api/basic_node/const_iterator.md, docs/mkdocs/docs/api/basic_node/constructor.md, docs/mkdocs/docs/api/basic_node/end.md, docs/mkdocs/docs/api/basic_node/extraction_operator.md, docs/mkdocs/docs/api/basic_node/index.md, docs/mkdocs/docs/api/basic_node/insertion_operator.md, docs/mkdocs/docs/api/basic_node/iterator.md, docs/mkdocs/docs/api/basic_node/mapping.md, docs/mkdocs/docs/api/basic_node/node.md, docs/mkdocs/docs/api/basic_node/operator[].md, docs/mkdocs/docs/api/basic_node/sequence.md, docs/mkdocs/docs/api/node_value_converter/to_node.md, docs/mkdocs/docs/api/ordered_map/at.md, docs/mkdocs/docs/api/ordered_map/constructor.md, docs/mkdocs/docs/api/ordered_map/emplace.md, docs/mkdocs/docs/api/ordered_map/find.md, docs/mkdocs/docs/api/ordered_map/operator[].md, docs/mkdocs/docs/tutorials/index.md, docs/mkdocs/mkdocs.yml, include/fkYAML/node.hpp, test/unit_test/test_data/extraction_operator_test_data.yml, test/unit_test/test_node_class.cpp
For serialization and deserialization of YAML nodes, insertion/extraction operators for basic_node template class have been added.  
They behave as wrapper functions of basic_node APIs for the features.  
This is also aimed to minimize the necessity of implementing unnecessarily long codes to achieve them.  
With the implementation of the new APIs, the test suite and the documentation has also been updated.
=> #195 Implement insertion/extraction operators for basic_node template class

docs/mkdocs/docs/tutorials/index.md, include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
As described [here](https://yaml.org/spec/1.2.2/#plain-style) in the YAML specification, plain (unquoted) string scalars can contain a space character within the character sequence if a space character is surrounded by non-space characters, for instance:
```yaml
test: This should be allowed but fkYAML throws an exception
```
fkYAML, however, did not support the exceptional case before this PR.  
So, this PR has fixed the deserialization procedure and supported the above case when the precondition is met with the YAML specification.
=> #200 Allow a space in unquoted strings

docs/mkdocs/docs/tutorials/index.md, include/fkYAML/detail/conversions/from_node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_custom_from_node.cpp
Currently, deserializing YAML sequence nodes only supports the `fkyaml::basic_node<...>::sequence_type` type.  
When attempting specialization for a vector of user-defined type objects, a user must call the specialization within a for-loop, which can be avoided by implementing partial specialization in fkYAML.  
So, this PR have resolved the issue described above.
=> #190 Support specialization of deserialization for a vector of user-defined type objects

include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/conversions/from_string.hpp, include/fkYAML/detail/conversions/to_node.hpp, include/fkYAML/detail/conversions/to_string.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/input_handler.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/iterator.hpp, include/fkYAML/detail/meta/detect.hpp, include/fkYAML/detail/meta/input_adapter_traits.hpp, include/fkYAML/detail/meta/node_traits.hpp, include/fkYAML/detail/meta/stl_supplement.hpp, include/fkYAML/detail/meta/type_traits.hpp, include/fkYAML/detail/node_ref_storage.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, include/fkYAML/detail/types/node_t.hpp, include/fkYAML/detail/types/yaml_version_t.hpp
Before this PR, library source files in the include directory uses different style for doxygen comments between public and private APIs.  
To make the source files organized, doxygen comment style is unified into `///` style, not `/* */` style.
=> Unified doxygen comment style

include/fkYAML/detail/input/deserializer.hpp, test/unit_test/test_deserializer_class.cpp
The YAML specification says mapping keys must be unique, but fkYAML doesn't check duplication of keys while parsing the input stream.  
To follow the specification, this PR has fixed the bug.  
Furthermore, to check that the fix works as expected, a new test case has also been added.
=> #205 Detect duplicate keys as an error

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
The YAML specification allows markers for the end of directives(---) and documents(...) to avoid ambiguity by declaring tags or having multiple YAML documents in the same YAML stream.  
So, this PR has supported the feature in fkYAML.  
Note that multiple YAML documents are not yet supported in fkYAML.  
Only the second or later YAML document will be merged into the first one during deserialization.
=> #207 Support markers for the end of directives/documents

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
As reported in #211, parsing single quoted strings causes an unexpected error.  
This PR has fixed the bug and modified some test cases to ensure that parsing single quoted strings does not cause any error.
=> #211 fixed bug in parsing single quoted strings

include/fkYAML/detail/input/deserializer.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_node_class.cpp
As reported in #211, parsing YAML document containing multiple indentation levels causes an unexpected error/result.  
This PR has fixed the way of handling indentation during parsing and modified some test cases to ensure fkYAML parses such YAML documents as it's expected.
=> #211 Fix indentation handling

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
The YAML specificates says that YAML processors must support unicode characters.  
To follow the specification, this PR has added support for escaped UTF-8 characters as inputs for deserialization.  
The exclusive test cases for the new support have also been added to the unit test app.
=> #209 support escaped unicode

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_input_handler.cpp, test/unit_test/test_lexical_analyzer_class.cpp
As reported in #217, fkYAML had a bug in parsing strings containing single quotes.  
So this PR has fixed the bug and modified test cases to ensure such strings can be parsed without an error.
=> #217 Fix parse errors on strings containing single quotes

docs/mkdocs/docs/api/basic_node/deserialize.md, docs/mkdocs/docs/api/basic_node/extraction_operator.md, docs/mkdocs/docs/tutorials/index.md, include/fkYAML/detail/encodings/utf8_encoding.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_input_adapter.cpp, test/unit_test/test_utf8_encoding_class.cpp
This PR has supported UTF-16 and UTF-20 for input characters passed to the deserialization process.  
Note that input characters must be encoded in the UTF-8 format when deserializing with `FILE*` or `std::istreams` objects.  
The deserialization process internally converts input characters into the UTF-8 encoded ones if they are encoded in the UTF-16 or UTF-32 format because the other features assume that the string values are encoded in the UTF-8 format.  
Furthermore, the test suite and documentation have also been updated along with the implementation above.
=> #209 support UTF-16 / UTF-32 for deserialization input characters

docs/mkdocs/docs/api/exception/index.md, docs/mkdocs/docs/api/exception/invalid_encoding.md, docs/mkdocs/docs/api/exception/parse_error.md, docs/mkdocs/docs/api/exception/type_error.md, docs/mkdocs/mkdocs.yml, include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/encodings/utf8_encoding.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/types/node_t.hpp, include/fkYAML/exception.hpp, include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_node_class.cpp, test/unit_test/test_utf8_encoding_class.cpp
Currently, fkYAML emits an `fkyaml::exception` object when some error is detected at runtime.  
The fkyaml::exception object only contains information of what kind of error detected without any runtime information.  
Such information makes it too difficult to dig into the actual issue causing the error.  
So, this PR has made error descriptions emitted from fkYAML more useful for further debugging.  
See the API documentation for the newly added exception classes and their error message contents.
=> #214 Emit more descriptive errors

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR has supported block style scalars for deserialization.  
Furthermore, unit test cases have also been added to ensure the deserialization of block style scalars works as it's expected.
=> #159 Support block scalar styles

docs/mkdocs/docs/api/basic_node/index.md, docs/mkdocs/docs/api/basic_node/operator_eq.md, docs/mkdocs/docs/api/basic_node/operator_ge.md, docs/mkdocs/docs/api/basic_node/operator_gt.md, docs/mkdocs/docs/api/basic_node/operator_le.md, docs/mkdocs/docs/api/basic_node/operator_lt.md, docs/mkdocs/docs/api/basic_node/operator_ne.md, docs/mkdocs/mkdocs.yml, include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
To prepare implementation in which non-string nodes are also supported as mapping keys, basic_node class operators for comparison have been added in this PR.  
Implementing those operator will enable basic_node class to be used as std::map::key_type.  
For detailed information about those operators, visit the API documentation pages.  
Furthermore, unit test cases and documentation have also been updated.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and …
=> #240 implement node comparison

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
In this PR, explicit block mappings and sequence/mapping keys have been supported in the deserialization feature.  
Also, new unit test cases have been added to ensure the newly supported features work as expected.  
--- …
=> #240 Support explicit block mappings & non-scalar nodes as mapping keys

test/unit_test/test_encode_detector.cpp
I've noticed that the test with Valgrind emits warnings about possible memory leaks.  
Although it's turned out missing callings of the `std::fclose()` function in the unit tests for encode detector is the cause and that doesn't affect the fkYAML library itself, it should be better to fix them.  
No other fixes are included in this PR.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work …
=> Fixed missing callings of `fclose()` in the unit tests

include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
In this PR, non-string-scalar nodes (like mappings or integer scalar nodes) have been supported in the `fkyaml::basic_node`'s constructor with `std::initializer_list`.  
The unit test has also been modified according to the changes above.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around …
=> #240 Support non-string-scalar node keys in basic_node ctor with std::initializer_list

.github/workflows/ubuntu.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
In this PR, GCC compiler versions have been added with which fkYAML is built/tested in GitHub Actions workflows.  
The list of supported compilers have also been updated both in README.md and the documentation hosted by the GitHub Pages.  
The compilers which are added to the list are as follows:
| Compiler                                 | Operating System   |
| ---------------------------------------- | ------------------ |
| Clang 17.0.4                             | Ubuntu 22.04.3 LTS |
| GCC 7.5.0                                | Ubuntu 22.04.3 LTS |
| GCC 8.5.0                                | Ubuntu 22.04.3 LTS |
---
- The C++11 support varies between different …
=> Add GCC compiler versions tested in GA workflows

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
According to the YAML spec, double quotation marks in a plain scalar are allowed. [link](https://yaml.org/spec/1.2.2/#733-plain-style).  
However, fkYAML mistakingly throws an exception against inputs which include such scalars like:
```yaml
foo: This is "Bar".
```
So, this PR has fixed the issue and the fix has also been tested by the modified test suite.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier …
=> Allow double quotation marks in plain scalars

include/fkYAML/detail/input/lexical_analyzer.hpp, test/unit_test/test_lexical_analyzer_class.cpp
According to the YAML spec, a dash(-) at the first character of a scalar is allowed. [link](https://yaml.org/spec/1.2.2/#733-plain-style)  
However, fkYAML didn't support such cases and threw an exception, e.g., with the following input:
```yaml
foo: -bar
```
So, this PR has fixed the issue and the fix has also been tested by the added test cases.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known …
=> Allow a dash(-) at the first character of a plain scalar

include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/input/deserializer.hpp, test/unit_test/test_custom_from_node.cpp
As described in #256, specialization of `from_node()` for std::map whose key/value types are both compatible with `basic_node`.  
Test cases related to the specialization have also been added.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or …
=> #256 Added specialization of from_node() for std::map with compatible key/value types

.github/workflows/amalgamation_check.yml, .github/workflows/clang_format_check.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
This PR has added some filters of triggering workflows depending on what kind of files have been changed.  
For, previously, all the workflows were activated on every commit regardless of what kind of changes have been made, which forces developers (especially me) to wait for an unnecessary amount of time, for example, modifying only the README file activates the Valgrind check.  
So, after merging this PR, commits on main/develop or other branches for PRs will activate the minimum required workflows.  
--- …
=> Added paths filter to regulate workflow executions

.github/workflows/publish_docs.yml, docs/examples/ex_macros_versions.output, docs/mkdocs/docs/tutorials/index.md
This PR has fixed some errors in building the documentation, introduced in #264.  
---
- Please refrain from proposing changes that would **break [YAML](https://yaml.org/) …
=> #229 Fix the documentation build errors

.github/workflows/macos.yml, include/fkYAML/detail/encodings/utf8_encoding.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp
As reported in #262, some jobs on GitHub Actions are not running unit tests since fkYAML unintendedly use C++14 features like binary integer literals and constexpr method with if statements.  
To keep fkYAML compatible with C++11, this PR has removed those keywords for now.  
What "for now" means is that fkYAML might introduce compile-time features in the future.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and …
=> Avoid using unintended C++14 features

docs/mkdocs/docs/tutorials/cmake_integration.md, docs/mkdocs/docs/tutorials/index.md
As reported in #262, this PR has fixed typos which needs to be `target_link_libraries()` in the CMakeLists.txt files in tutorials.  
No other changes have been made.  
---
- Please …
=> fixed typos which needs to be target_link_libraries() in tutorials

include/fkYAML/detail/encodings/encode_detector.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/macros/cpp_config_macros.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
As described in #237, since C++20, the string literal `u8""` has changed to return a `char8_t[N]` object, instead of a `char[N]` object, which has broken backward compatiblity with the code compiled with C++17 or earlier.  
fkYAML is intended to work C++11 and later, and so this PR has added a workaround to resolve the issue described above.  
--- …
=> #237 Support char8_t in deserialization

docs/examples/ex_basic_node_is_alias.cpp, docs/examples/ex_basic_node_is_alias.output, docs/examples/ex_basic_node_is_anchor.cpp, docs/examples/ex_basic_node_is_anchor.output, docs/examples/ex_macros_versions.output, docs/mkdocs/docs/api/basic_node/index.md, docs/mkdocs/docs/api/basic_node/is_alias.md, docs/mkdocs/docs/api/basic_node/is_anchor.md, docs/mkdocs/mkdocs.yml, include/fkYAML/detail/conversions/to_string.hpp, include/fkYAML/detail/node_property.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp, test/unit_test/test_serializer_class.cpp
This PR improved the way of handling anchors/aliases by classifying them as node properties.  
Along the way, new basic_node APIs, `is_anchor()` and `is_alias()`, have been added with descriptions in the documentation.  
--- …
=> Modify handling node properties

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
As described in #272, a block sequence which contains a comment unexpectedly crashes the fkYAML deserializer.  
So, this PR has fixed the crash with the reported input.  
---
- Please …
=> #272 Fix parse error on a block sequence containing a comment within

.github/workflows/macos.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
Since [the macos-13 GA runner image](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) has been officially released, some workflow jobs which use that runner image have been added.  
Furthermore, the list of supported compilers has been updated.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain …
=> Add workflow jobs with the macos-13 runner image

.github/workflows/ubuntu.yml, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
As reported in #275, plain scalars containing flow indicators (`[]`, `{}`, and `,`) caused either incorrect parse result or parse errors.  
That was because fkYAML couldn't handle context (whether a current node is within flow context or not).  
This PR has fixed the reported issues, and now fkYAML can successfully parse such plain scalars.  
--- …
=> #275 Fixed parse error on plain scalars containing flow indicators

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
As reported in #277, the parser generate a incorrect YAML node tree from plain scalars which start with special string values (such as `null` or `True`).  
This PR has fixed the issue by changing the timing where such special values are detected.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work …
=> #277 Fixed incorrect parse result from plain scalars starting with special values

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
Fixes #282 by not traversing up to the parent node immediately after parsing flow-mapping values, as code elsewhere in the deserializer implementation was also traversing to the parent node, meaning either a crash occurred if there was only one parent, or a double-traversal occurred and sibling values were appended to the grandparent instead.
--- …
=> #282 Don't traverse up to the parent node immediately after parsing a flow-mapping value

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR has fixed the parser crash reported in #281.  
The root cause was that the parser didn't handle white spaces and comments after a block sequence/mapping key.  
Now the parser handles those characters correctly and doesn't crash nor generate incorrect YAML node tree, which is confirmed with the updated test suite.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing …
=> #281 Fixed the parser crash due to comments right after a sequence block key

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
As reported in the issue #288, the the parser & lexer implementations didn't cover mapping entries split across newlines.  
To fix that, the handling of key separators (`:`) have been moved from the lexer to the deserializer, and defer checking the existence of a key separator followed by a node associated to a block mapping key.  
To validate the above changes, the test suite has been updated with some new test cases.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang …
=> #288 Fixed incorrect parse results from mapping entries split across newlines

.github/workflows/amalgamation_check.yml, .github/workflows/clang_format_check.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/macos.yml, .github/workflows/publish_docs.yml, .github/workflows/release_package.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
This PR has resolved the warnings against using GitHub Actions depending on Node.js 16.  
For more information, visit the following links:
* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
* https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
No other changes have been made in this PR.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and …
=> Resolve warnings against using Node.js 16

include/fkYAML/detail/encodings/encode_detector.hpp, include/fkYAML/detail/string_formatter.hpp, include/fkYAML/detail/types/node_t.hpp, include/fkYAML/exception.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_string_formatter.cpp
This PR has made small changes in the way of formatting error messages for the `fkyaml::exception` 
and its derived class objects from using `std::stringstream` to the C-style formatting using `std::vsnprintf()`.  
(I honestly wanted to use std::format, but it's been available since C++20 and I don't want to add any external dependencies, other than C++ standards, to the library itself.)  
The error message contents themselves are not changed.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC …
=> modied the way of formatting error messages for exception objects

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR addresses #292 by checking if the lexer is in a flow context before treating flow indicators, commas, or colons as terminating plain unquoted strings.
---
- Please refrain from …
=> #292 Better handling for flow indicators in permitted scalar contexts

include/fkYAML/detail/encodings/encode_detector.hpp, include/fkYAML/detail/encodings/utf_encode_t.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/input_handler.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/output/serializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_encode_detector.cpp, test/unit_test/test_input_handler.cpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR has improved the way of handling UTF encoded inputs by:
* dropping information about the existence of a byte order mark (BOM) from inputs during the creation of an input adapter object since the information won't be needed by the lexer and the deserializer, and
* preparing a normalized input buffer which is guranteed to be encoded in the UTF-8 format in the `input_handler` class before the actual start of the deserialization process.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 …
=> Improve handling UTF encoded inputs

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR addresses the issue #302 by the following changes:
* The handling of alias nodes has been fixed in both the parser and the lexer since they didn't consider alias mapping keys.
* The deserialization of scalar nodes has been changed to correctly parse anchor/alias nodes.
* The extraction of anchor names has been changed since some invalid patterns were not correctly detected.
* The test suite has been updated to validate the above changes.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC …
=> #302 Fixed parse error on alias mapping keys

test/unit_test/test_input_adapter.cpp
This PR has fixed errors reported by Valgrind.  
The errors were due to missing `std::fclose()` calls after opening a test data file in the input_adapter class test cases.  
So no changes have been made to the library source codes.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these …
=> Fix Valgrind error in the test suite

include/fkYAML/detail/conversions/from_string.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_scanner.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_scanner_class.cpp
In #305, YAML tags are now supported in YAML scalar nodes.  
Depending on the tag type, however, unnecessary conversion could occur in the lexer before determining the parsed scalar type based on the given tag.  
So, all conversions triggered by the lexer have been changed so that they are defered until the convertion result is actually requested by the deserializer.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and …
=> Defer scalar conversions

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR adds support of tags for container nodes while improving the handlings of node properties in general in the deserialization feature.  
Moreover, the test cases for the `fkyaml::detail::basic_deserializer` class, especially their test case names and the way of classifying them, have been reorganized for better readability.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to …
=> support tags for container nodes with some cleanup in test suite

.github/workflows/macos.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
Since the macOS14 GA runner image has been officially released, some workflow jobs which use that runner image have been added.  
Furthermore, the list of supported compilers has been updated according to the above change.  
--- …
=> Add workflow jobs with the macOS14 runner image

README.md, docs/mkdocs/docs/api/basic_node/deserialize.md, docs/mkdocs/docs/api/basic_node/get_value.md, docs/mkdocs/docs/api/node_value_converter/from_node.md, docs/mkdocs/docs/api/operator_literal_yaml.md, docs/mkdocs/docs/index.md, include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/meta/stl_supplement.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_input_adapter.cpp, test/unit_test/test_node_class.cpp
This PR has added the `std::basic_string_view` support in the conversion from a string node to a native string value only when compiled with C++17 or better.  
Also, test cases for the deserialization feature have been added for the explicit support for the `std::basic_string_view<CharT>` types.  
The documentation has also been updated according to the above changes.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 …
=> #294 Support std::basic_string_view

docs/mkdocs/docs/api/basic_node/serialize.md, include/fkYAML/detail/output/serializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_serializer_class.cpp
This PR has added the feature of serializing container tags with related test cases (scalar tags are already supported in #305 ).  
Furthermore, the format with which the serialization feature complies are added to the documentation for the `basic_node::serialize` function.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from …
=> #181 Serialize container tags

include/fkYAML/detail/encodings/utf8_encoding.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/exception.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_utf8_encoding_class.cpp, tool/clang_format/run_clang_format.sh
Before this PR, not only `utf8_encoding` class but also `lexical_analyzer` and `input_adapter` types knows too much of the concrete UTF-8 encoding format so those classes can get the actual number of bytes for a target UTF-8 character.  
So, this PR has added the feature with which the actual number of bytes can be aquired from the first byte of a target UTF-8 character.  
Also, `invalid_encoding` exception class constructor requires a `std::array<int, N>` parameter and the instanciation consts unnecessarily.  
To fix that, the constructor now receives a `std::initializer_list<uint8_t>` parameter.  
---
- The C++11 support varies between different **compilers** and …
=> Query the count of UTF-8 character bytes

CMakeLists.txt
This PR has modified the CMakeList file to set the unit test app project as the Visual Studio startup project for convenience (1) if the target compiler is some version of Microsoft Visual C++ or the likes and (2) if the fkYAML project is built as the main project.  
No other changes have been made.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 …
=> Set the unit test app as the Visual Studio startup project

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
fkYAML in the latest develop branch emits a parse error when an input buffer starts with a node which is not a block mapping, like the following valid YAML snippets:  
(block sequence)
```yaml
- 123
- foo
- 3.14
```
(flow sequence)  
```yaml
[123, foo, 3.14]
```
(flow mapping)  
```yaml
{foo: 123, true: 3.14}
```
So, this PR has fixed the error and added some test cases to validate the changes.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or …
=> Fix parse error on the first node which isn't a block mapping

.github/workflows/windows.yml, include/fkYAML/detail/input/input_adapter.hpp, single_include/fkYAML/node.hpp
This PR has added workflow items to test Win32 builds.  
Also, a warning due to implicit casting from signed to unsigned was found while making the change, and it has also been resolved.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other …
=> Add workflows items to test Win32 builds

tool/amalgamation/CHANGES.md, tool/amalgamation/amalgamate.py
Running amalgamation on Windows produces huge diff due to changes from LF to CRLF, which is a valid behavior of Python's built-in `open()` function without specifying the `newline` parameter.  
That isn't desirable and would confuse contributors who want to run amalgamation on Windows.  
So, this PR has fixed the above issue by modifying the `amalgamate.py` script, updating the `tool/amalgamation/CHANGELOG.md` file.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 …
=> Force LF newline codes in the amalgamated file

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
The fkYAML parser in the latest develop branch crashes with the following valid YAML snippets (taken from [the official YAML test suite `Z9M4/in.yaml`](https://github.com/yaml/yaml-test-suite/blob/data-2022-01-17/Z9M4/in.yaml)):  
```yml
%TAG !e! tag:example.com,2000:app/
---
- !e!foo "bar"
```
After some investigation, it's turned out that the parser doesn't process directive end markers (denoted with `---`) properly.  
So, this PR has fixed the parser's issue and added a test case to validate the change.   …
=> Fixed parser crashes on a sequence right after the directives end marker

scripts/run_amalgamation.sh, scripts/run_clang_format.sh
When the Bash scripts for running clang-format and amalagamation on Windows, they ends up with errors which says no such file/directory.  
This is because (1) Python distributions for Windows have no `python3` executable and (2) binaries are stored in the `venv\Scripts` directory, not in the `venv/bin` directory, when Python venv module is used on Windows.  
To fix the above issues, this PR has added platform switches using the output from the `uname` command.  
Both on Ubuntu22.04 with WSL2 and Windows10 with Git for Windows (2.44.0-windows.1), the scripts now work as expected.  
---
- The C++11 support varies between different **compilers** and versions. Please note …
=> Fixed no such file/directory error when running Bash scripts on Windows

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
The current fkYAML parser throws a `parse_error` exception when a plain/single-quoted scalar contains backslashes (\) which are allowed in the YAML spec.  
For example, the following valid YAML snippet cannot be parsed correctly because of that wrong implementation:  
```yaml
plain: foo\bar.yaml
single quoted: 'foo\bar.yaml'
```
This PR has fixed the above issue and updated some related test cases which have wrong expectations.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and …
=> Allow backslashes in plain/single-quoted scalars

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed parse errors which the current parser emits on root block sequence containing child block sequences, like the following valid YAML snippet (slightly modified version of [the official YAML test suite `3ALJ`](https://github.com/yaml/yaml-test-suite/blob/data-2022-01-17/3ALJ/in.yaml)):  
```yaml
- - foo
- 123
- 3.14
```
The test case with the above snippet has also been added to the test suite to validate the change.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and …
=> Fixed parse error on root block sequence with child block sequences

include/fkYAML/detail/encodings/encode_detector.hpp, include/fkYAML/detail/encodings/utf_encodings.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/position_tracker.hpp, include/fkYAML/exception.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_utf_encodings.cpp
This PR has improved the internal implementation for the deserialization feature with the following changes:  
* The stacks of indentations and nodes were managed separately but are now handled as a single stack variable with context state types.
* The values for tracking the current input position are now of the `uint32_t` type, not of the unnecessarily large `size_t` type which was used before with no convincing reason.
* The traversal codes which find a parse context with a matching indentation have been improved by removing unnecessary traversals.
* Unnecessary variables/type-aliasings are removed which became unused during previous refactorings of the lexer and the input/unicode handlings.
In addition, unnecesary node object instanciations are removed in the test cases for the …
=> Refactor deserialization process

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_custom_from_node.cpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed parse errors which the current parser emits on a block sequence containing child flow style containers (either sequence and/or mapping), like the following valid YAML snippet (based on [the official YAML test suite `YD5X`](https://github.com/yaml/yaml-test-suite/blob/data-2022-01-17/YD5X/in.yaml)):  
```yaml
- [username, identifier, score]
- [booker12, 9012      , 61.25]
- [grey07  , 2070      , 84.50]
- {foo: false, null: 123}
- {true: 3.14, bar: [0x30,0o30]}
```
While modifying implementation to fix the above issue, the way of managing parse contexts has also been corrected by adding the variation of parse context states.  
---
- The C++11 support …
=> Fix parse error on block sequences with child flow style container nodes

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR has fixed parse errors which the current parser emits on a block sequence containing child block mappings, like the following valid YAML snippet (taken from [the official YAML test suite `229Q`](https://github.com/yaml/yaml-test-suite/blob/data-2022-01-17/229Q/in.yaml)):
```yaml
-
name: Mark McGwire
hr:   65
avg:  0.278
-
name: Sammy Sosa
hr:   63
avg:  0.288
```
The parser now interprets `-` followed by a newline code (either CR, LF, or CR+LF) as a block sequence entry prefix and the change is validated by adding the above YAML snippet to the test suite.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of …
=> Fixed parse error on block sequences with child block mappings split by a newline code

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
The latest lexer emits a wrong error on anchor names which contains colons(:).  
According to the YAML spec, anchor names consist of printable characters (including colons) EXCEPT newline codes, white spaces and flow indicators.  
So, this PR has corrected the way of extracting an anchor name from the input source to follow the spec by modifying the lexer and the related test cases.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual …
=> Allow false error on anchor names containing colons (:)

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
The current lexer lacks implementation to unescape the escape sequence of a backslash(\) and 0x09 to a horizontal tab(\t) as the YAML standard specifies [here](https://yaml.org/spec/1.2.2/#57-escaped-characters).  
This PR has added the missing escaping and a related test case.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain …
=> Escape backslash(\) + 0x09 to a horizontal tab (\t)

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed an assertion failure (in the debug mode) or an incorrect parse result (in the release mode) each of which occurs when the parser tries to deserialize a YAML snippet where node properties (a tag, a anchor, or both) is specified to a child block sequence, like the following one:  
```yaml
foo: !!seq # This property causes the assertion failure
- true
- 123
```
The root cause was that the parser didn't set node properties to an appropriate block sequence node and tried to parse a subsequent scalar node with the `!!seq` tag.  
Several test cases have also been added to check if the above issue has been resolved.  
---
- The C++11 support varies between …
=> Fixed error on node properties for child block sequences

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed wrong parse results from YAML which contains the non-first node pair whose value is a block sequence, like the YAML snippet in the issue #347 due to the wrong tracing back to a parent mapping node.  
--- …
=> Fix wrong parse result from mappings containing the non-first block sequence

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed parse errors on flow container keys like the following valid YAML snippet:  
```yaml
{foo: bar}: 123
[true,false]: 3.14
```
The root cause is that the fkYAML deserializer wrongly assumed that flow containers weren't used as a mapping key.  
To validate the fix, the test suite has also been updated by adding several relevant test cases for the deserializer.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio …
=> Fix parse error on flow container keys

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has added error detection of missing flow value separators ( `,` ) in flow containers and some test cases for the detection.  
Before this PR, the deserializer mistakenly succeeded in parsing invalid YAML snippets which lacks necessary value separators, like the following:  
```yaml
foo: [123  true, 3.14]
bar: {baz: 123  qux: false}
```
--- …
=> Detect errors on missing flow value separators

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
As reported in the issue #347, the latest parser mistakenly emits the parse errors on empty flow containers like:
```yaml
foo: {}
bar: []
```
They are caused because the PR #350 lacked implementation for empty flow containers.  
So, this PR has fixed them by adding the missing implementation and added some test cases to validate the changes.  
--- …
=> Fix parse error on empty flow containers

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed parse errors on explicit mappings as a block sequence entry like the following valid YAML snippet:
```yaml
- ? foo: 123
: bar: true
- ? - baz
: - null
```
The root cause was that the fkYAML parser just didn't assume explicit mappings as a block sequence entry.  
So, implementation has been added for such nodes with some update of the test suite which validates the functionality.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or …
=> fixed parse error on explicit mappings as a block sequence entry

CMakeLists.txt, Makefile, README.md, scripts/run_clang_format.bat, scripts/run_clang_format.sh, tool/benchmark/CMakeLists.txt, tool/benchmark/README.md, tool/benchmark/macos.yml, tool/benchmark/main.cpp, tool/benchmark/result_debug.log, tool/benchmark/result_release.log
This PR has added a dedicated benchmarking tool for fkYAML on the parsing speed.  
The tool compares the parsing speed against the following existing YAML libraries for C/C++:
* [libfyaml](https://github.com/pantoniou/libfyaml) ([v0.9](https://github.com/pantoniou/libfyaml/releases/tag/v0.9))
* [rapidyaml](https://github.com/biojppm/rapidyaml) ([v0.6.0](https://github.com/biojppm/rapidyaml/releases/tag/v0.6.0))
* [yaml-cpp](https://github.com/jbeder/yaml-cpp) ([0.8.0](https://github.com/jbeder/yaml-cpp/releases/tag/0.8.0))
See the [README.md](https://github.com/fktn-k/fkYAML/blob/develop/tool/benchmark/README.md) file for more details.  
---
- The C++11 support varies …
=> Add benchmarking tool

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
The current parser mistakenly emits parse errors on small negative integer keys like the following valid YAML snippet:
```yaml
{-4: bar}
```
This was caused by the wrong lookahead implemented for tokens which start with a hyphen(-).  
So, this PR has fixed it and the above snipet is now parsed successfully.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete …
=> Fix parse error on smal negative integer keys

Makefile, README.md, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/position_tracker.hpp, include/fkYAML/detail/input/scalar_scanner.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_scalar_scanner_class.cpp, tool/benchmark/result_debug.log, tool/benchmark/result_release.log
In this PR, some refactorings have been made for better performance, including:
* cleaning up basic_node's destructor
* optimizing the process of scanning multiline scalars
* improving the scanning of scalar contents for type detection
Also, the Make target for benchmarking contains a wrong fixed path and performance of debug builds were not correctly measured.  
However, the performance of debug builds seems to need some more work for trustworthy results, which is why the performance data of debug builds have been removed (possibly revoked in the future).  
--- …
=> Refactor for optimization

.github/workflows/windows.yml, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp
This PR fixes the following compile errors on Windows:
* errors from too few template parameters for `node_value_converter` when compiled with C++20 or newer and Visual Studio 2022, as reported in #357
* errors from ambiguous parameter type for `basic_node::deserialize(ItrType, ItrType)` called from the user defined literal `operator"" _yaml(...)` when compiled with C++11, C++14, C++17 without the `/permissive-` flag.
Also, workflow jobs have been added to test builds with existing C++ standards and Visual Studio 2022.  
--- …
=> Fix compile errors on Windows

.github/workflows/ubuntu.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md, test/unit_test/CMakeLists.txt
This PR adds support of icpx compilers.  
Intel compilers use fast floating points by default and (sometimes too aggressively) warn against the usages of nans and infinities.  
fkYAML, however, uses nans and infinities to manage YAML node values.  
So, in building the unit test app, `-fp-model=precise` is used as a workaround.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to …
=> Support Intel icpx compiler

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
The current parser can't detect missing end-of-directives markers (---) between directives and contents like the following invalid YAML snippet:
```yaml
%YAML 1.2
foo: bar
```
So this PR has added detection of the lacking of those markers and several test cases to validate the added implementation.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 …
=> Detect missing the end of directives markers (---)

docs/examples/ex_basic_node_serialize_docs.cpp, docs/examples/ex_basic_node_serialize_docs.output, docs/mkdocs/docs/api/basic_node/index.md, docs/mkdocs/docs/api/basic_node/serialize_docs.md, docs/mkdocs/mkdocs.yml, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp, test/unit_test/test_serializer_class.cpp
This PR has added the new support of serializing multiple YAML documents by implementing the `fkyaml::basic_node::serialize_docs()` function.  
It accepts a vector of basic_node objects like the `fkyaml::basic_node::deserialize_docs()` function returns, and returns a string as the serialization result with separation lines (`...`) between documents.  
See the updated API documentation for details about the function.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 …
=> Support serializing multiple YAML docs

include/fkYAML/detail/output/serializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_serializer_class.cpp
The current serializer changes alias names when they are used as a mapping key.  
For example, serializing the following YAML snippet:
```yaml
foo: &A bar
*A : baz
```
the serializer emits the following wrong result since alias names can contain colons:
```yaml
foo: &A bar
*A: baz # alias name mistakenly becomes "*A:".
```
So, this PR has fixed the above issue and now the serializer emits correct alias keys.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and …
=> Fix bug in serializing alias keys

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_input_adapter.cpp
The current parser didn't allow trailing commas in flow mappings/sequences like the following valid YAML snippet:
```yaml
foo: {
null: 123,
baz: true,
}
bar: [
3.14,
false,
]
```
The YAML spec allows both putting/omitting trailing commas in flow mappings/sequences.  
So, this PR has modified the implementation to allow putting trailing commas by modifying state management for flow contexts.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or …
=> Allow trailing comma in flow mapping/sequence

.github/workflows/macos.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
The GitHub Actions runner image for macOS 11 has been deprecated, and the CI jobs running with the image now don't work anymore.  
So, this PR has removed them and AppleClang compiler support has therefore been shrunk.  
The supported compilers list has also been updated in the documentation.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. …
=> Remove CI jobs running with macOS 11

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed a bug reported in #368 as well as related, underlying ones by modifying implementation for parsing node properties.  
The major bugs are as follows:  
* no line advancement happens after parsing node properties for mappings as a block sequence entry (the reported bug),
* no parsing happens for mapping values whose node properties are user defined (i.e., neither `!!map` nor the likes), and
* incorrect node traversal to select a mapping key node with a desired indentation.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supp …
=> #368 Fix line advancement after node props

docs/mkdocs/docs/api/basic_node/serialize.md, docs/mkdocs/docs/api/basic_node/serialize_docs.md, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/output/serializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_serializer_class.cpp
fkYAML currently ignores node properties for the root node unintentionally, like parsing the following   valid YAML snippet:  
```yaml
--- !!map
foo: bar
```
They are obviously allowed in the spec.  
So this PR has fixed the serializer/deserializer to properly handle them and added some test cases to validate the changes.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing …
=> Apply node properties for the root node

include/fkYAML/detail/conversions/from_node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
This PR has fixed the error in converting a node's value into a native floating point value, as reported in the issue #366.  
The root cause was that calling the `std::min()` function to get the minimum possible value of the target type: the function returns minimum possible **positive** normal value of a floating point value type, not the minimum possible **negative** value; the appropriate function to call is the  `std::lowest()` for that purpose.  
In short, the real cause was the library coudn't convert a node value whose value is a floating point value equal to/less than 0.  
So, this PR has fixed the issue by replacing the calling of `std::min()` with `std::lowest()` on node-to-float conversions.  
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIBUT …
=> #366 Fix node-to-float conversion error if node's value is <= 0

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
The current fkYAML doesn't allow the document end marker (...) omitted before a new YAML document like the following YAML snippet (extracted from the yaml-test-suite's 35KP/in.yaml):  
```yaml
--- !!map
? a
: b
--- !!seq
- !!str c
--- !!str
d
e
```
Parsing the above YAML with fkYAML causes a false parse error which says "invalid end-of-directives marker (---) found in the contents.".  
To resolve the false error, this PR has changed the implementation to allow the document end marker omitted, and the library thus assumes no directives preceeded in the next YAML document instead.  
---
- The C++11 support varies between different **compilers** and versions. Please note …
=> Allow the document end marker omitted

include/fkYAML/detail/input/input_adapter.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_input_adapter.cpp
This PR has fixed the newline code normalization of CR+LF into LF contained in a given file for deserialization, which is the root cause of the bug reported in the issue #375.  
Before the fix, CR+LF newline codes were normalized mistakenly into CR, which broke the subsequent deserialization process which intentionally ignores the existence of CR for optimization.  
By correcting the normalization logic, CR+LF are now successfully normalized into LF.  
Furthermore, since the normalized input value checks were somehow dropped in the input_adapter module test cases, the appropriate checks have also been added.
---
- The C++11 support varies between different …
=> #375 Fix newline code normalization in UTF-8 encoded file input

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR has fixed a wrong parse result generated from a YAML document which contains a block sequence as a nested block mapping value in the middle like the following:  
```yaml
foo:
bar:
- 123
baz: true
```
The `baz: true` part mistakenly became a part of the `bar` block sequence's entry.  
For the parser didn't get back to the proper node when a block sequence entry prefix (`- `) is as much indented as the parent mapping keys before parsing the `baz` key. (if the prefix is more indented than the keys, the parse result was correct.)  
So, this PR has fixed the node traversal logic and added a new test case to validate the change.  
With the fix, the above YAML document is now parsed as expected.  
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIBUTING.md …
=> Fix wrong parse result from a block sequence as a nested block mapping value

include/fkYAML/detail/input/input_adapter.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_input_adapter.cpp
This PR fixes the issue with attempting to call a deserialization function on a nonexistent stream (std::ifstream), reported in issue #378.
Previously, when attempting to read data from a nonexistent stream, an infinite loop would occur, trying to read data that was not there.
Now, if the stream is empty, an exception will be thrown, which can be handled using a try-catch block.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual …
=> Throw exception when loading a nonexistent stream

include/fkYAML/detail/input/scalar_scanner.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_scanner_class.cpp
As reported in the issue #380, the current parser emits an error on parsing a floating point value which ends with a dot.  
That is because, while scanning a parsed scalar, the parser mistakenly assumes decimals after a dot.  
However, the spec explicitly allows omitting decimals after a dot [here](https://yaml.org/spec/1.2.2/#1032-tag-resolution) as the regular expression for the float tag.  
So, this PR has fixed implementation to follow the spec, and the updated parser now correctly parse such floating point values.  
To validate the changes, some relevant test cases have also been added to the test suite.  
---
- The C++11 support varies between different …
=> Fix error on parsing a floating point value which ends with a dot

.github/workflows/coverage.yml, .github/workflows/format_check.yml
With this PR, I try to fix workflow errors on a PR from a fork repository since some workflows need to write permission to the PR or acceess to secrets to push an automatically created commit.  
One way to resolve them is change the trigger event from pull_request to pull_request_target, just as this PR does.  
Note, according to [the official document](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target), that can be insecure against stealing secrets or running a malicious code.  
So, further changes will be required to increase security in the future since this is first aid to the errors.  
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIBUTING.md) file for detailed …
=> Fix workflow errors on PRs from fork repos

.github/workflows/coverage.yml, .github/workflows/format_check.yml
This PR fixes conditional branching based on the trigerring event name (pull_request_target or push) to not try to comment to a PR if the triggering event name is push.  
---
- Please …
=> Fix conditional branching for pull_request_target events

include/fkYAML/detail/encodings/utf_encode_detector.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/meta/type_traits.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_utf_encode_detector.cpp
This PR has improved implementations for UTF encoding detection by separating detector impl classes accordingly to the given char type or by reducing an unnecessary number of array element accesses during the detection.  
No changes should appear to the library users since this is just a refactoring.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 …
=> Improve UTF encoding detection

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
The current library can't detect invalid contents specified in block scalar headers, like the followings:  
```yaml
foo: |10 # the indentation must be between 1 and 9.
```
```yaml
foo: >++ # too many chomping indicators
```
```yaml
foo: |invalid # neither chomping nor indentation indicators must be a comment.
```
So, this PR has fixed the implementation for parsing block scalar headers and also added some relevant test cases.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), …
=> Fix detecting invalid contents of block scalar headers

include/fkYAML/detail/conversions/to_node.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/node_attrs.hpp, include/fkYAML/detail/node_property.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_node_attrs.cpp
This PR has modified internal node attributes management.  
The latest basic_node class hold a `fkyaml::node_type` to track the current node value type, and a pair of a `fkyaml::detail::anchor_status_t` & a `uint32_t` to reach an anchored node if the node itself is an alias node.  
Although node attributes requires 12 bytes (4 bytes each), they can be compressed into 4 bytes using bits, which is what is done in this PR.  
Since this is just a refactoring of internal data management, nothing should change from the viewpoint of library users.  
Actually this PR is a kind of preparation for per-node serialization style specification (stored with unused bits) like:  
* block style or flow style
* single quoted, double quoted or plain string
* decimal, octal, hexadecimal integer
* etc...
Note …
=> Refactor node attributes management

Makefile, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/position_tracker.hpp, include/fkYAML/detail/input/scalar_scanner.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_scanner_class.cpp
In this PR, the lexer implementation has been refactored by:  
* reducing the number of string copies during lexical analysis
* improving the ways of block/flow scalar scannings
No changes have been made regarding public APIs.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these …
=> Refactor lexical analysis

include/fkYAML/detail/macros/cpp_config_macros.hpp, single_include/fkYAML/node.hpp
Although this library depends on C++11 by default, some implementations are switched based on the value of the `__cplusplus` macro to utilize some nice-to-have features available since C++14 or better.  
However, the MSVC compilers don't set an appropriate value to that macro if the `/Zc:__cplusplus` option isn't specified.  
That issue forces those who use this library with some MSVC compiler to stick to C++11 features even if they explicitly use C++14 or better by specifying options like `/std:c++14`.  
As explicitly described [here](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/), the `_MSVC_LANG` macro is always set a correct value.  
So, as many other C++ libraries do, this library refers to `_MSVC_LANG` if some MSVC compiler is used to compile, and …
=> Use _MSVC_LANG macro when compiled with MSVC for C++ standard detection

README.md, include/fkYAML/detail/encodings/uri_encoding.hpp, include/fkYAML/detail/encodings/yaml_escaper.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/position_tracker.hpp, include/fkYAML/detail/input/scalar_scanner.hpp, include/fkYAML/detail/meta/input_adapter_traits.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/detail/str_view.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_input_adapter.cpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_position_tracker_class.cpp, test/unit_test/test_scalar_scanner_class.cpp, test/unit_test/test_str_view_class.cpp, test/unit_test/test_uri_encoding_class.cpp, test/unit_test/test_utf_encodings.cpp, test/unit_test/test_yaml_escaper_class.cpp, tool/benchmark/result_debug.log, tool/benchmark/result_release.log
This PR has significantly reduced the number & size of string copies and subsequent heap allocations during parsing of YAML sources by the following major changes:
* use `fkyaml::detail::str_view` class which is newly implemented as a minimal implementation of `std::string_view` (since C++17) even when the library is built with C++11 or C++14 so that inspections into YAML sources are executed more effectively
* avoid copying YAML sources into a `std::string` object if they don't contain CR newline codes and are an array/container which has contiguous byte array to store actual characters (like `char [N]`, `std::vector` or `std::string`)
* reduced unnecessary `std::string` instanciations during the parsing
As a result of the above changes, the benchmark scores of this library has increased …
=> Reduce string copies in parse

include/fkYAML/detail/assert.hpp, include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/conversions/scalar_conv.hpp, include/fkYAML/detail/encodings/utf_encode_detector.hpp, include/fkYAML/detail/encodings/yaml_escaper.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/tag_resolver.hpp, include/fkYAML/detail/iterator.hpp, include/fkYAML/detail/macros/cpp_config_macros.hpp, include/fkYAML/detail/meta/input_adapter_traits.hpp, include/fkYAML/detail/str_view.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_utf_encode_detector.cpp
This PR intoduces `FK_YAML_LIKELY` and `FK_YAML_UNLIKELY` macros which conditionally expand to:
* `[[likely]]` and `[[unlikely]]` C++ attributes if available (preferred since they should be compiler agnostic as part of C++ standard attributes)
* `__builtin_expect(!!(expr), 1)` and `__builtin_expect(!!(expr), 0)` invocations if `__builtin_expect` is available (like GCC like compilers)
* just `!!(expr)` if the above two aren't available (like MSVC compilers with C++11-17)
Along with the above change, some preprocessor macros have also been tidied.  
--- …
=> Use likely/unlikely if available

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp
The current deserializer doesn't properly handle the '%' character based on whether it processes document directives or contents.  
As the spec specifies [here](https://yaml.org/spec/1.2.2/#912-document-markers), if it processes document directives, '%' as the first character should be interpretted as the beginning of a directive; and if it processes document contents, '%' can be used as the first character of a scalar:  
```yaml
%YAML 1.2
---
%this key: is valid # the first '%' is not the beginning of a directive
```
So, this PR has modified the lexer so it can properly decide whether '%' is the beginning of a directive or the first character of a scalar.  
---
- The …
=> Accept % as first scalar character

tool/benchmark/CMakeLists.txt, tool/benchmark/main.cpp
This PR has fixed warnings and errors when compiling the benchmarking app with MSVC compilers and made it just work.  
No other changes have been made.  
No benchmarking results on Windows is uploaded yet, and please hold on for a while.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around …
=> Fix compile warnings/errors when benchmarker app is compiled with msvc

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
The current deserialization feature cannot detect invalid flow indicators contained in tag shorthands, either primary(!tag), secondary(!!tag) or named(!handle!tag), though the spec explicitly defines them as invalid characters when they appear in a tag shorthand in the "Tag Shorthands" section of https://yaml.org/spec/1.2.2/#691-node-tags.  
```yaml
!!str, this tag: is invalid
```
To fix it, this PR has corrected related implementations in the lexer, and test cases have also been added to validate the changes.  
--- …
=> Fix URI validation for tag shorthands

include/fkYAML/detail/conversions/to_string.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_serializer_class.cpp
This PR fixes #405 by appending ".0" during float scalar serialization when a float is actually an integer. Without the appending, the serialization result would be interpreted as an integer scalar on using it as the input of deserialization.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work …
=> Fix float scalar serialization when a float is actually an integer

README.md, include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/conversions/scalar_conv.hpp, include/fkYAML/detail/input/block_scalar_header.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_parser.hpp, include/fkYAML/detail/input/scalar_scanner.hpp, include/fkYAML/detail/input/tag_t.hpp, include/fkYAML/detail/macros/cpp_config_macros.hpp, include/fkYAML/detail/str_view.hpp, include/fkYAML/detail/types/lexical_token_t.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_parser_class.cpp, tool/benchmark/results/result_debug_citm_catalog_json.txt, tool/benchmark/results/result_debug_citm_catalog_yml.txt, tool/benchmark/results/result_debug_ubuntu_yml.txt, tool/benchmark/results/result_release_citm_catalog_json.txt, tool/benchmark/results/result_release_citm_catalog_yml.txt, tool/benchmark/results/result_release_ubuntu_yml.txt
In this PR, scalar parsing has been optimized by separating actual parsing of scalar contents from lexical analysis.  
That has significantly reduced unnecessarily complicated conditional branches and heap allocations for intermediate values.  
The performance of the whole deserialization process has therefore been increased by 5 Mi/s on average.  
|parsed YAML file|Before this PR|After this PR|
|---|---|---|
|ubuntu.yml|50.4621Mi/s|55.1393Mi/s|
|citm_catalog.json|75.5534Mi/s|82.9931Mi/s|
|citm_catalog.yml|32.7921Mi/s|35.152Mi/s|
--- …
=> Optimized scalar parsing

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR fixes a bug which has been introduced in the PR #409.  
Before the fix, infinite loops happened after parsing a final empty block scalar since updating current position was missed in the lexer.  
The above issue can be reproduced by trying to parse the following YAML:  
```yaml
- |+
```
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. …
=> Fix infinite loops after parsing final empty block scalar

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR fixes wrong parse results from YAML documents which contains only one scalar (either flow or block) as described in the issue #406.  
The root cause was that the current parser overestimates the root node is a mapping if the first node is a scalar.  
So, the overestimation is corrected by determining the root node type based on the lexical token type, and some test cases are added to validate the chages.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and …
=> Fix wrong parse result from single scalar document

include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt
Newer versions of Clang (including AppleClang) compilers emits the `-Wdeprecated-literal-operator` warning against the definitions of literal operators `fkyaml::literals::yaml_literals::operator "" _yaml()` since a space before the suffix `_yaml` is deprecated from C++23.  
Even if the active C++ standard is not C++23, however, compiling this library with the `-Wdeprecated` compile option causes the warning.  
So, as a workaround, the `-Wdeprecated-literal-operator` warning is disabled while declaring `_yaml` literal operators.  
--- …
=> Disable -Wdeprecated-literal-operator warnings

.github/workflows/macos.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
This PR expands AppleClang compiler support on macOS 14 & 15.  
The supported compiler list has also been updated according to the above changes.  
---
- Please refrain from proposing …
=> GA workflow jobs with more AppleClang versions on macOS

docs/examples/ex_basic_node_get_value.cpp, docs/examples/ex_basic_node_get_value.output, docs/examples/ex_macros_versions.output, docs/mkdocs/docs/api/basic_node/get_value.md, include/fkYAML/detail/conversions/from_node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
This PR adds numeric scalar conversions, such as `float` to `int`, inside the `basic_node::get_value` function.  
```cpp
fkyaml::node n = 1.23; // type == node_type::FLOAT
int i = n.get_value<int>(); // i == 1 (`double` is internally converted to `int`)
bool b = n.get_value<bool>(); // b == true (`double` is internally converted to `bool`)
```
This change was suggested [here](https://github.com/fktn-k/fkYAML/issues/366#issuecomment-2181062261) by @ARessegetesStery to provide easier and more natural access methods to YAML node values in a similar way in which C++ handles primitives.   
The conversions follows these rules:  
* If the YAML node value is a **null** (node_type::NULL_OBJECT), the value can be converted to:
* `false` (boolean)
* `0` (integer)
* `0.0` (floating point)
* If the …
=> Numeric scalar conversions inside basic_node::get_value API

docs/examples/ex_basic_node_get_value.cpp, docs/examples/ex_basic_node_get_value.output, docs/mkdocs/docs/api/basic_node/get_value.md, include/fkYAML/detail/conversions/from_node.hpp, include/fkYAML/detail/macros/cpp_config_macros.hpp, include/fkYAML/detail/meta/detect.hpp, include/fkYAML/detail/meta/stl_supplement.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_custom_from_node.cpp, test/unit_test/test_node_class.cpp
This PR added support of much more STL container types in `basic_node::get_value()` API.  
For details, please visit [the documentation](https://fktn-k.github.io/fkYAML/api/basic_node/get_value/) for the API.  
Moreover, the API now accepts basic_node template instance types as its return type to allow conversions to container types whose element type is a basic_node template instance type, e.g., `std::array<fkyaml::node, 3>` or `std::unordered_map<fkyaml::node, fkyaml::node>`.  
When this library is compiled with C++17 or greater, `std::optional` can be the return type which holds some converted value on success or `std::nullopt` otherwise.  
Types which were convertible from nodes should still be convertible in the same way.
---
Read the …
=> Support more STL types in from_node

docs/mkdocs/docs/api/macros.md, include/fkYAML/detail/encodings/utf_encodings.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/input_adapter.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_parser.hpp, include/fkYAML/detail/macros/cpp_config_macros.hpp, include/fkYAML/detail/meta/stl_supplement.hpp, include/fkYAML/detail/node_attrs.hpp, include/fkYAML/detail/types/node_t.hpp, include/fkYAML/node.hpp, include/fkYAML/node_type.hpp, include/fkYAML/yaml_version_type.hpp, single_include/fkYAML/node.hpp
The current library deliberately implements some dead codes to suppress warnings against default switch-cases. However, such codes are considered as a possible path from the compiler's view as much frequently as the other "valid" cases.  
So, in this PR, such codes have been replaced by calling a function which calls one of the following functions (upper one has more priority) so that a compiler can know the codes are actually unreachable and can be optimized away:  
* [`std::unreachable()`](https://en.cppreference.com/w/cpp/utility/unreachable) (since C++23)
* [`__assume(false)`](https://learn.microsoft.com/en-us/cpp/intrinsics/assume?view=msvc-170) (MSVC)
* [__builtin_unreachable()](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005funreachable) (other …
=> Use std::unreachable() or similar compiler specific extensions for dead but necessary code

include/fkYAML/detail/meta/stl_supplement.hpp, single_include/fkYAML/node.hpp
This PR fixes unintended coverage loss due to no calls to the fkyaml::detail::unreachable() function.  
Since the function is intended not to be called in any expected way, I've just excluded it from the coverage targets.  
--- …
=> Exclude detail::unreachable() from coverage target

include/fkYAML/detail/encodings/uri_encoding.hpp, single_include/fkYAML/node.hpp, test/unit_test/CMakeLists.txt
This PR fixes the [C4800](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4800?view=msvc-170) warnings when this library is compiled with a MSVC compiler as reported in the issue #429.  
The warnings are now resolved by `static_cast`ing the result of `std::isalnum()` as `bool`.  
Furthermore, the test suite is now built with the compile option `/w44800` to avoid a possible regression in the future (the C4800 warning is desabled by default and even with the compile option `/W4`).  
--- …
=> Resolve the C4800 warning when compiled with MSVC

include/fkYAML/detail/input/scalar_parser.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_scalar_parser_class.cpp
This PR has fixed the issue reported in #428, that is, conversion failure from a string to either an integer or a floating point value throws a `parse_error` exception.  
The error should be recovered by treating the source scalar as a string scalar instead if the scalar is not tagged with `!!int`, `!!float` or the equivalents.  
Note that conversion to null and boolean scalars are not considered as recoverable since their presentations are restricted to literals defined in the YAML spec, e.g., `null`, `true` or `False`.  
--- …
=> Stop throwing parse_error on string-to-int/float conversion failures if not forced with tag

.github/workflows/macos.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
Due to the support policy changes as described in the issue https://github.com/actions/runner-images/issues/10703, Xcode versions to use in GitHub Actions workflow jobs have been updated.  
Now, those jobs uses
* Xcode 15.x versions with the macos-14 runner image and
* Xcode 16.x versions with the macos-15 runner image.
Furthermore, since the macos-12 runner image will be removed on 12/3/24 as described in the issue https://github.com/actions/runner-images/issues/10721, workflow jobs using the runner image have been removed, and therefore
* Xcode 13.x versions are no longer tested but
* Xcode 14.x versions are still tested using the macos-13 runner image.
The supported compilers list has also been updated according to the above changes.
---
Read the …
=> Update GitHub Actions workflow jobs using macOS related runner images

include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_parser.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_parser_class.cpp
In this PR, parsing multiline plain (unquoted) scalars has been implemented, which was described as a restriction in the PR #344  
> **The flow line folding for plain scalars is not yet supported** since the deserialization feature is not yet ready for that feature. It will, however, surely be supported in the future. Until the feature gets ready, please make such a scalar be either single or double quoted.
Before this PR, multiline plain scalars seemed to be parsed with no error but the parse result was just incorrect since its data structure was different from the expected one. (I know this was terrible in debugging...)  
The library can now successfully parses such scalars and the result has its correct data structure.  
We can simply pass this YAML
```yaml
key: this line
is a …
```
=> Support parsing multiline plain scalars

include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
As described in [the YAML specification (7.1. Alias Nodes)](https://yaml.org/spec/1.2.2/#71-alias-nodes), any properties (anchor and tag) must not be specified to an alias node.  
Although the library emits an error if a tag is specified to an alias node, it doesn't if an anchor is specified to an alias node.  
```yaml
&anchor foo: !!str *anchor # this is treated as an error.
---
&anchor foo: &anchor2 *anchor # this is not treated as an error, but it should be.
```
So, in this PR, the implementation has been fixed so the library would throws an parse_error if an anchor is specified to an alias node.  
---
- The C++11 support varies between different **compilers** and …
=> Emit error if an anchor is specified to an alias

include/fkYAML/detail/input/block_scalar_header.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_parser.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_scalar_parser_class.cpp
In this PR, several bugs in parsing block literal/folded scalars (due to wrong implementations) have been fixed.
1. A leading empty line which is more indented than the first non-empty line  
```yaml
foo: |
foo # 2 spaces as indentation
```
* Before: no error was emitted
* After: `parse_error` is thrown
2. A non-empty line which is less indented than the content indentation level  
but more indented than the base indentation level  
```yaml
foo: |
text
invalid # this line is less indented than the content indentation level (2)
```
* Before: no error was emitted
* After: `parse_error` is thrown
3. A more-indented empty line in block folded scalar contents  
```yaml
foo: >
bar
```
* Before: parsed as `foo: "\t  bar"`
* After: parsed as `\n\t \nbar`
Furthermore, although the current …
=> Fixed bugs in parsing block scalars

.github/workflows/ubuntu.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md, include/fkYAML/detail/encodings/utf_encode_detector.hpp, include/fkYAML/detail/encodings/yaml_escaper.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, include/fkYAML/detail/input/scalar_parser.hpp, include/fkYAML/detail/input/tag_resolver.hpp, include/fkYAML/detail/node_property.hpp, include/fkYAML/detail/str_view.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_utf_encode_detector.cpp, test/unit_test/test_utf_encodings.cpp
This PR adds more GCC & Clang versions to use in GitHub Actions workflows:
* GCC: 4.8, 5, 6
* Clang: 3.4, 19
Changes in the library implementations have been made to resolve warnings when compiled with the above older compilers.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these …
=> Add more GCC & Clang versions to use in GitHub Actions workflows

docs/examples/CMakeLists.txt, docs/examples/ex_basic_node_empty.cpp, docs/examples/ex_basic_node_empty.output, docs/examples/ex_basic_node_get_value.cpp, docs/examples/ex_basic_node_size.cpp, docs/examples/ex_basic_node_size.output, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR fixes parse error in building example files for basic_node::deserialize() function.  
The root cause was that #432 introduced a bug in parsing an input which
* begins with a newline and
* contains a plain scalar as a mapping value with indentation on the second line
The above two conditions caused invalid indentation detections.  
This bug can be reproduced by running this cpp file:  
```cpp
#include <fkYAML/node.hpp>
int main() {
std::string input = R"(
foo: true
bar: 123
baz: 3.14
)";
return 0;
}
```
The above snipet now runs as expected by fixing detection of indentation during deserialization.  
Moreover, some minor fixes have been made to resolve warnings during example builds.  
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIBUTING.md) …
=> Fix parsing input which begins with a newline & indentation

Makefile, docs/mkdocs/docs/api/basic_node/begin.md, docs/mkdocs/docs/api/basic_node/end.md, docs/mkdocs/docs/api/basic_node/index.md, docs/mkdocs/mkdocs.yml, include/fkYAML/detail/iterator.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_iterator_class.cpp, test/unit_test/test_node_class.cpp
This PR adds the following changes:  
* The following legacy container types are added to the basic_node template class as its member types.  
The `iterator` and `const_iterator` of `basic_node` refer to them when instantiating their types.  
|name|description|associated type|
|---|---|---|
|value_type|type of elements of a container node|basic_node|
|reference|type of reference to an element of a container node|basic_node&|
|const_reference|type of const reference to an element of a container node|const basic_node&|
|pointer|type of pointer to an element of a container node|basic_node*|
|const_pointer|type of const pointer to an element of a container node|const basic_node*|
|size_type|type to represent container node sizes|std::size_t|
|size_type|type to represent differences between …
=> Make node iterators compatible with different value type const-ness

include/fkYAML/detail/conversions/to_string.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_serializer_class.cpp
This PR fixes the issue which has been itroduced by the PR #407 and is reported [here](https://github.com/fktn-k/fkYAML/issues/405#issuecomment-2523117670).  
During the conversion from a floating point value to a string, ".0" is appended only when the following conditions are met:  
1. the floating point value is actually an integer
2. no scientific notation is used for serialization
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual …
=> Fix round-trip issue in float serialization using scientific notation

CMakeLists.txt, test/cmake_add_subdirectory_test/project/CMakeLists.txt, test/cmake_fetch_content_test/project/CMakeLists.txt, test/cmake_find_package_test/project/CMakeLists.txt, test/cmake_target_include_directories_test/project/CMakeLists.txt
Starting with CMake 3.31 (used in the ubuntu-24.04 runner), cmake_minimum_required() emits a warning against the minimum required version begin less than 3.10 like [this](https://github.com/fktn-k/fkYAML/actions/runs/12259711278/job/34202574102#step:3:7).  
To resolve it, this PR adds a policy_max version for cmake_minimum_required() calls as described in [the official document](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html).  
Note the same warning is still emitted in the catch2's cmakelists file, where I cannot do anything...
--- …
=> Resolve CMake deprecation warning

docs/mkdocs/docs/api/basic_node/get_value.md, include/fkYAML/detail/conversions/from_node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp
This PR adds support for `std::forward_list` in conversion from a basic_node by calling `get_value()` and `get_value_inplace()`.  
The documentation has also been updated according to the above change.  
Furthermore, since the current test suite covers not 100% of lines/branches of the codebase (I just didn't check the coverage score), some test cases have been added. Now the test suite covers 100% of the lines/branches again!    
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and …
=> support std::forward_list in from_node

README.md, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, tool/benchmark/results/result_debug_citm_catalog_json.txt, tool/benchmark/results/result_debug_citm_catalog_yml.txt, tool/benchmark/results/result_debug_ubuntu_yml.txt, tool/benchmark/results/result_release_citm_catalog_json.txt, tool/benchmark/results/result_release_citm_catalog_yml.txt, tool/benchmark/results/result_release_ubuntu_yml.txt
In this PR, the lexer implementation has been optimized by reducing redundant object creations and data copies.  
The effect of the optimization is shown by the updated benchmark results.  
| parsed file       | processed bytes per second (before) | processed bytes per second (after) |
| ----------------- | ----------------------------------- | ---------------------------------- |
| ubuntu.yml        | 55.1393Mi/s                         | 60.1886Mi/s                        |
| citm_catalog.json | 82.9931Mi/s                         | 91.1523Mi/s                        |
| citm_catalog.yml  | 35.152Mi/s                          | 36.0492Mi/s                        |
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIBUTING.md) file for detailed information. …
=> Optimize lexer implementation

Makefile, include/fkYAML/detail/input/deserializer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_deserializer_class.cpp
This PR fixes detecting bad indentations for block sequence/mapping entries as reported in the issue #449.  
Also, the way of managing parse contexts has been improved by separating `BLOCK_SEQUENCE_ENTRY` from `BLOCK_SEQUENCE` in the enum class `context_state_t` for the above fix.  
That allows for block sequence entries to be empty and they are now properly parsed.  
```yaml
- foo
- - 123
-
-
- bar
```
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), …
=> Fix bad indentation detection for block collection entries

include/fkYAML/detail/output/serializer.hpp
Fixed a bug where serialize didn't write out empty vectors and mappings in a correct way. I have not added a test case, but I tested it in my code and it behaved as expected. Adding a test case at some point would be good.
Regarding the test cases, I couldn't get that to run when I followed the instructions, and don't have time to dig into why. I did test it using my own code though, and it seems to work.
---
- [X ] Changes are described in the pull request or in a referenced [issue](https://github.com/fktn-k/fkYAML/issues). …
=> fix: Fixed a bug where serialize didn't write out empty vectors and mappings

include/fkYAML/detail/output/serializer.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_serializer_class.cpp
This PR adds some test cases which validate serialization results from empty collection nodes.  
The bug fix itself has already been addressed in the PR #456, so the changes in the library sources are only for improvements in readability and coverage.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that …
=> Add test cases for serializing empty collection nodes

include/fkYAML/detail/output/serializer.hpp
Described in title. No test cases done. 
---
- Please refrain from proposing changes that would **break [YAML](https://yaml.org/) specifications**. If you propose a conformant extension …
=> Fix: made sure that empty documents just serialize to [] or {}

.github/workflows/ubuntu.yml, tests/unit_test/test_serializer_class.cpp
This PR adds test cases for serializing a root empty sequence/mapping fixed by the PR #460.  
---
- Please refrain from proposing changes that would **break [YAML](https://yaml.org/) …
=> Add test cases for serializing root empty collections

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/tag_resolver.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_tag_resolver_class.cpp
This PR removes some redundant string allocations for tag/anchor names in the deserialization.  
---
- Please refrain from proposing changes that would **break [YAML](https://yaml.org/) …
=> Improve handling node properties in deserialization

.github/workflows/ubuntu.yml, docs/docs/api/basic_node/constructor.md, examples/apis/basic_node/constructor_6.cpp, examples/apis/basic_node/constructor_6.output, include/fkYAML/detail/conversions/to_node.hpp, include/fkYAML/detail/exception_safe_allocation.hpp, include/fkYAML/detail/meta/detect.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_node_class.cpp
This PR has added builtin implementations of the `to_node()` function which are used when constructing a `fkyaml::basic_node` object with arbitrary types.  
Before this PR, minimal builtin implementation was provided so that converting to a basic_node object from its template parameter types (like `fkyaml::basic_node::sequence_type`), which wasn't much helpful.  
Now, any object of many existing STL container types (like `std::vector`, `std::unordered_map` or `std::tuple`) can be used as an argument of the `fkyaml::basic_node` constructor.  
See the updated documentation for supported STL container types.  
Furthermore, you can, of course, provide your own custom `to_node()` implementation for non-standard types just as before and such a type can be used as the element type of STL …
=> Add to_node() implementations for STL container types

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
This PR disables the `fail-fast` option for the jobs with different build types(Debug/Release) and/or compiler versions in order to make it easier to debug issues in some specific sets of build configurations.  
Nothing else is changed.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around …
=> Disable the fail-fast option for GitHub Actions workflow jobs

include/fkYAML/detail/conversions/to_node.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_node_class.cpp
This PR fixes wrong conversions from `std::tuple<>` to `basic_node`.  
That was introduced in the PR #465.  
`std::tuple<>` was converted to a null node while an empty sequence was (and still is) converted to `std::tuple<>`.  
Now, `std::tuple<>` and an empty sequence are guranteed to be converted to each other.  
```cpp
// BEFORE the fix
std::tuple<> t {};
fkyaml::node n = t; // `n` used to be converted as a null scalar node.
// AFTER the fix
fkyaml::node n = t; // `n` is now converted as an empty sequence node.
```
--- …
=> Fix conversions from empty tuples

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_lexical_analyzer_class.cpp
This PR makes changes to allow for a flow mapping value to be specified right after the ":" mapping value indicator if its key is JSON-like (surrounded by indicators like `{}`, `[]`, `""` or `''`) since the YAML specification allows that for JSON compatibility (see [here](https://yaml.org/spec/1.2.2/#742-flow-mappings)).  
With the changes, the following YAML (and minified JSON) is now parsed without any problem.  
```yaml
{
"foo":true,
'bar':false,
{[1,2,3]:"baz"}:3.14
}
```
```json
{"foo",true,"bar":false,"baz":null}
```
--- …
=> Allow ':' adjacent to a flow mapping value right after a JSON-like key

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_lexical_analyzer_class.cpp
Although the YAML specification doesn't allow a comment to be followed right after non-break characters, the current lexer implementation doesn't detect such an invalid comment usage.  
```yaml
"foo"# invalid comment
```
This PR therefore fixes the implementation so the lexer emits an error when the '#' comment prefix doesn't meet all the following checks:  
* it is the first character in the input buffer, or
* it follows after a white space character (` ` or `\t`) or a line break ('\n' or `\r\n`)
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/READM …
=> Fix comment prefix check

README.md, include/fkYAML/detail/encodings/utf_encodings.hpp, include/fkYAML/detail/input/input_adapter.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_utf_encodings.cpp, tools/benchmark/results/result_debug_citm_catalog_json.txt, tools/benchmark/results/result_debug_citm_catalog_yml.txt, tools/benchmark/results/result_debug_ubuntu_yml.txt, tools/benchmark/results/result_release_citm_catalog_json.txt, tools/benchmark/results/result_release_citm_catalog_yml.txt, tools/benchmark/results/result_release_ubuntu_yml.txt
This PR improves UTF encode validation and line break normalization for input buffers regarding both readability and performance, by removing unnecessary conditional branches and optimizing the way of scanning input buffer contents.  
As for performance, see the updated benchmark results.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. …
=> Refactor UTF encode validation & line break normalization

include/fkYAML/detail/input/input_adapter.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_deserializer_class.cpp, tests/unit_test/test_input_adapter.cpp
This bug was introduced in the previous PR #470 and this PR fixes it by adding a check of the size read from an input stream.  
Several test cases for a variety of empty inputs have also been added so a similar bug can be found before merging changes in the future.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing …
=> Fix error in parsing empty inputs

include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, tests/unit_test/test_deserializer_class.cpp, tests/unit_test/test_lexical_analyzer_class.cpp
This PR fixes document marker (`---` and `...`) detections since the current lexer implementation doesn't check whether those markers is at the beginning of a line or not, which makes it impossible to distinguish the following tokens with different meanings in YAML grammer.  
```yaml
--- # this is a directives end marker
--- # this is a plain scalar
```
Also, the parser now emit an error if a document marker is found in a flow collection since the marker terminates the parsing and the corresponding ending character of the flow collection is regarded as missing:  
```yaml
[   # the corresponding `]` character is not found in this document since
--- # this marker terminates the parsing of the document.
]
```
---
Read the [CONTRIBUTING.md](https://github.com/fktn-k/fkYAML/blob/develop/CONTRIB …
=> Fix document marker detections

.github/workflows/ubuntu.yml, examples/apis/basic_node/deserialize_docs_char_array.cpp, examples/apis/basic_node/deserialize_docs_iterators.cpp, examples/apis/basic_node/deserialize_docs_string.cpp
This PR fixes examples which contains incorrect indentation of document markers.  
Furthermore, a workflow job is added to check example builds to avoid similar issues in the future.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other …
=> Fix example builds with incorrectly indented document markers
