fktn-k/fkYAML

.github/workflows/cmake_debug.yml, .github/workflows/cmake_package_debug.yml, .github/workflows/cmake_package_release.yml, .github/workflows/cmake_release.yml, CMakeLists.txt, include/fkYAML/Node.hpp
I added configurations of CI/CD for this repository.  
The configured GitHub workflows will check:
- if building & testing procedures are successful on ubuntu-latest/windows-latest/macos-latest,
- and if packaging procedure is also successful on those platforms.
Close #2
=> #2 configure CI/CD

include/fkYAML/LexicalAnalyzer.hpp, test/unit_test/CMakeLists.txt, test/unit_test/LexicalAnalyzerTest.cpp, test/unit_test/LexicalAnalyzerTest.hpp, test/unit_test/main.cpp
Block sequence YAML nodes are supported for deserialization.  
Some tests for the above deserialization are then added to the unit test app.
=> #4 supported block sequence deserialization

.github/workflows/codeql.yml
CodeQL Analysis have been added to GitHub Actions workflows.  
This is an experimental implementation, and so some bugfixes may be needed later on.
=> add CodeQL analysis to CI

.github/workflows/coverage.yml, include/fkYAML/Iterator.hpp, include/fkYAML/Node.hpp, test/unit_test/CMakeLists.txt, test/unit_test/IteratorClassTest.cpp, test/unit_test/LexicalAnalyzerClassTest.cpp
The unit test cases for Iterator class have been added.  
All lines have been covered except unreachable ones.
=> #20 add unit test for iterator

README.md
I added descriptions to README.md for users of the fkYAML library.  
Descriptions for developers will be added in the near future.
=> #17 add descriptions in readme

CODEOWNERS, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md
Some documentation files about this project have been added.
=> #88 add more documents

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, CMakeLists.txt, Makefile, test/unit_test/CMakeLists.txt
To enhance effectiveness in development, Makefile and GA workflow configs have been modified to execute CMake build process in parallel.  
Also, some redundant configurations have been removed from build scripts.
=> #135 optimize build scripts

include/fkYAML/detail/input/input_handler.hpp, test/unit_test/CMakeLists.txt, test/unit_test/test_input_handler.cpp
Test cases for `input_handler` class have been added.  
They cover all the lines/branches in the class.  
Related URL: #150.
=> #150 Add unit tests for input_handler class

.reuse/templates/fkYAML.commented.jinja2, Makefile
This PR has updated the procedures of version-up script to make it up to date with the current project structure.  
No changes in the library source codes.
=> Updated header template and target file for version up script

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Descriptions for the contribution guide have been improved in this PR.  
Also, a template for PRs has been added as well.
=> Improved contribution guide

LICENSE.txt, README.md, docs/mkdocs/docs/home/license.md
In this PR, I have changed the copyright since its content varies from place to place and that's confusing.  
---
- Please refrain from proposing changes that would **break …
=> Update copyright description

appveyor.yml
This PR added a config file for AppVeyor.  
The configuration includes build/unit-testing on Visual Studio 2015 and Visual Studio 2017 which haven't been supported since GitHub Actions doesn't provide runner images for those environments.  
Since any build/unit-testing have not been triggered, the documentation is intentionally left untouched.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not …
=> added config file for AppVeyor

README.md, docs/mkdocs/docs/home/community_support.md, docs/mkdocs/docs/home/supported_compilers.md, docs/mkdocs/docs/tutorials/cmake_integration.md
For the next release, this PR has updated the contents of the documentations and fixed some typos and ambiguous expressions.  
---
- Please refrain from proposing changes that would …
=> Updated documents

test/cmake_add_subdirectory_test/CMakeLists.txt, test/cmake_fetch_content_test/CMakeLists.txt, test/cmake_find_package_test/CMakeLists.txt, test/cmake_target_include_directories_test/CMakeLists.txt, test/unit_test/CMakeLists.txt, test/unit_test/test_custom_from_node.cpp, test/unit_test/test_deserializer_class.cpp, test/unit_test/test_encode_detector.cpp, test/unit_test/test_exception_class.cpp, test/unit_test/test_from_string.cpp, test/unit_test/test_input_adapter.cpp, test/unit_test/test_iterator_class.cpp, test/unit_test/test_lexical_analyzer_class.cpp, test/unit_test/test_node_class.cpp, test/unit_test/test_node_ref_storage_class.cpp, test/unit_test/test_ordered_map_class.cpp, test/unit_test/test_position_tracker_class.cpp, test/unit_test/test_scalar_scanner_class.cpp, test/unit_test/test_serializer_class.cpp, test/unit_test/test_string_formatter.cpp, test/unit_test/test_tag_resolver_class.cpp, test/unit_test/test_uri_encoding_class.cpp, test/unit_test/test_utf8_encoding_class.cpp
This PR has organized the contents of the test suite, for example, the naming convention of the unit test cases or renaming of existing unit test cases whose name was too ambiguous to grasp what is tested.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with …
=> Organized the contents of the test suite

test/unit_test/test_deserializer_class.cpp
This PR has fixed the C6262 warning against the parser test function for block mappings by reorganizing related test cases without changing the inputs or assertion checks.  
No other changes have been made.  
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with …
=> Fix the C6262 warning on Windows

include/fkYAML/detail/document_metainfo.hpp, include/fkYAML/detail/input/deserializer.hpp, include/fkYAML/detail/input/tag_resolver.hpp, include/fkYAML/detail/node_property.hpp, include/fkYAML/detail/output/serializer.hpp, include/fkYAML/node.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_node_class.cpp, test/unit_test/test_tag_resolver_class.cpp
This PR has improved the way of managing anchor/alias nodes by sharing the anchor node table among nodes.  
The process of deserializing such nodes and have also been modified according to the above change.
---
- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/fktn-k/fkYAML/blob/develop/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with …
=> Improve anchor alias node management

include/fkYAML/detail/input/lexical_analyzer.hpp, single_include/fkYAML/node.hpp, test/unit_test/test_lexical_analyzer_class.cpp
This PR has added the feature of deserializing the flow line folding for single/double quoted scalars with the following restrictions:  
* ***The flow line folding is being allowed for implicit keys*** despite that it's explicitly forbidden in the YAML specification. This is because of the lack of implementation to determine if scalars are implicit keys or not but such a logic is going to be implemented and the folding will become not allowed in the future.  
* ***The flow line folding for plain scalars is not yet supported*** since the deserialization feature is not yet ready for that feature. It will, however, surely be supported in the future. Until the feature gets ready, please make such a scalar be either single or double quoted.  
---
Read the …
=> support flow line folding for single/double quoted scalars

.github/workflows/ubuntu.yml, README.md, docs/mkdocs/docs/home/supported_compilers.md
[Describe your pull request here. Please read the description below and make sure you follow the checklist.]  
---
- Please refrain from proposing changes that would **break …
=> added gcc14 & clang18 to the compiler version list for testing

fkYAML.natvis, tool/natvis_generator/fkYAML.natvis.j2
After the PR #388, the fkYAML.natvis file has not been updated and has been corrupted due to internal changes in some basic_node's private members. This PR fixes the corruption.  
---
- …
=> Updated natvis file

.github/workflows/release_package.yml
This PR updates existing GitHub Actions workflow jobs for release artifacts.  
From the next release on, new tar.gz & zip archives are to be also published.  
They contain only minimum required files (roughly the top CMakeLists.txt & include/single_include directories) to be used as a CMake project since this repository now contains many files which are not needed by a client app which just uses fkYAML.  
See [the workflow result](https://github.com/fktn-k/fkYAML/actions/runs/12400834786) for actual contents of release artifacts.  
--- …
=> Update workflow jobs for release artifacts
